import { ObjectId } from 'mongodb';
import { Lookup } from '#common/models/index.js';
import { Usuario } from './user/index.js';
import { Expediente } from './expediente/index.js';

export interface DB {
  users: Usuario[];
  expedientes: Expediente[];
  unidadProponentes: Lookup[];
  roles: Lookup[];
}

export const db: DB = {
  users: [
    {
      _id: new ObjectId('67e29f6498ec8fa00c141af1'),
      nombre: 'Carlos',
      apellido: 'González Pérez',
      email: 'carlos.gonzalez@example.com',
      telefono: '910123456',
      movil: '620123456',
      rol: {
        id: '677d15fd24c5646a1f7f69c0',
        nombre: 'Usuario-Administrador',
      },
      esResponsable: true,
      esProponente: true,
      esAutorizante: false,
      esContraseñaTemporal: false,
      contraseña: 'carlos123',
      unidad: {
        id: '677d1539c3cb57a1f7b57e77',
        nombre: 'Unidad E',
        code: 'E1',
      },
    },
    {
      _id: new ObjectId('67e2a2a01faec0c33a18c24a'),
      nombre: 'María',
      apellido: 'Martínez López',
      email: 'maria.martinez@example.com',
      telefono: '910234567',
      movil: '620234567',
      rol: {
        id: '677d1609d7dfb3725db36e45',
        nombre: 'Usuario-Escritura',
      },
      esResponsable: true,
      esProponente: true,
      esAutorizante: true,
      esContraseñaTemporal: false,
      contraseña: 'maria456',
      unidad: {
        id: '677d15df0b8b68a6601e826a',
        nombre: 'Unidad B',
        code: 'B2',
      },
    },
    {
      _id: new ObjectId('67e2a2a9bdf6ec804964701e'),
      nombre: 'Juan',
      apellido: 'Rodríguez Sánchez',
      email: 'juan.rodriguez@example.com',
      telefono: '910345678',
      movil: '620345678',
      rol: {
        id: '677d160e6d98cb2a17428884',
        nombre: 'Usuario-Lectura',
      },
      esResponsable: false,
      esProponente: false,
      esAutorizante: false,
      esContraseñaTemporal: true,
      contraseña: 'temp480',
      unidad: {
        id: '677d15f51ea7df458590b5f9',
        nombre: 'Unidad C',
        code: 'C4',
      },
    },
    {
      _id: new ObjectId('67e2a2b17f7177a8b57ceed7'),
      nombre: 'Laura',
      apellido: 'García Ruiz',
      email: 'laura.garcia@example.com',
      telefono: '910456789',
      movil: '620456789',
      rol: {
        id: '677d160e6d98cb2a17428884',
        nombre: 'Usuario-Lectura',
      },
      esResponsable: false,
      esProponente: false,
      esAutorizante: false,
      esContraseñaTemporal: true,
      contraseña: 'temp480',
      unidad: {
        id: '677d15f51ea7df458590b5f9',
        nombre: 'Unidad C',
        code: 'C4',
      },
    },
    {
      _id: new ObjectId('67e2a2bb61e3836ad14d746e'),
      nombre: 'Miguel',
      apellido: 'Fernández Gómez',
      email: 'miguel.fernandez@example.com',
      telefono: '910567890',
      movil: '620567890',
      rol: {
        id: '677d160e6d98cb2a17428884',
        nombre: 'Usuario-Lectura',
      },
      esResponsable: false,
      esProponente: false,
      esAutorizante: false,
      esContraseñaTemporal: true,
      contraseña: 'temp480',
      unidad: {
        id: '677d15f51ea7df458590b5f9',
        nombre: 'Unidad C',
        code: 'C4',
      },
    },
  ],
  unidadProponentes: [
    { id: '677d1539c3cb57a1f7b57e77', nombre: 'Unidad E', code: 'E1' },
    { id: '677d15df0b8b68a6601e826a', nombre: 'Unidad B', code: 'B2' },
    { id: '677d15f51ea7df458590b5f9', nombre: 'Unidad C', code: 'C4' },
  ],
  roles: [
    {
      id: '677d15fd24c5646a1f7f69c0',
      nombre: 'Usuario-Administrador',
    },
    {
      id: '677d1609d7dfb3725db36e45',
      nombre: 'Usuario-Escritura',
    },
    {
      id: '677d160e6d98cb2a17428884',
      nombre: 'Usuario-Lectura',
    },
  ],
  expedientes: [
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceed7'),
      clase: 'Administrativo',
      titulo: 'Solicitud de Información',
      adjudicataria: 'Juan Pérez',
      estado: 'En Proceso',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceed8'),
      clase: 'Técnico',
      titulo: 'Informe Técnico',
      adjudicataria: 'María López',
      estado: 'Finalizado',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceed9'),
      clase: 'Financiero',
      titulo: 'Informe Financiero',
      adjudicataria: 'Carlos García',
      estado: 'Pendiente',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceeda'),
      clase: 'Legal',
      titulo: 'Informe Legal',
      adjudicataria: 'Laura Martínez',
      estado: 'En Revisión',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceedb'),
      clase: 'Administrativo',
      titulo: 'Solicitud de Modificación',
      adjudicataria: 'Miguel Fernández',
      estado: 'Aprobado',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceedc'),
      clase: 'Técnico',
      titulo: 'Informe de Progreso',
      adjudicataria: 'Ana Torres',
      estado: 'En Proceso',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceedd'),
      clase: 'Financiero',
      titulo: 'Informe de Gastos',
      adjudicataria: 'Luis Martínez',
      estado: 'Pendiente',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceede'),
      clase: 'Legal',
      titulo: 'Informe de Cumplimiento',
      adjudicataria: 'Sofía García',
      estado: 'Finalizado',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceedf'),
      clase: 'Administrativo',
      titulo: 'Solicitud de Aprobación',
      adjudicataria: 'Pedro González',
      estado: 'En Revisión',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceee0'),
      clase: 'Técnico',
      titulo: 'Informe de Evaluación',
      adjudicataria: 'Clara López',
      estado: 'Aprobado',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceee1'),
      clase: 'Legal',
      titulo: 'Solicitud de Revisión',
      adjudicataria: 'Isabel Ramírez',
      estado: 'Pendiente',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceee2'),
      clase: 'Financiero',
      titulo: 'Análisis de Presupuesto',
      adjudicataria: 'Javier Torres',
      estado: 'Finalizado',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceee3'),
      clase: 'Técnico',
      titulo: 'Inspección Técnica',
      adjudicataria: 'Carmen Díaz',
      estado: 'En Proceso',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceee4'),
      clase: 'Administrativo',
      titulo: 'Petición Administrativa',
      adjudicataria: 'Andrés Morales',
      estado: 'Aprobado',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceee5'),
      clase: 'Legal',
      titulo: 'Resolución Judicial',
      adjudicataria: 'Elena Navarro',
      estado: 'Finalizado',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceee6'),
      clase: 'Financiero',
      titulo: 'Informe de Auditoría',
      adjudicataria: 'Pablo Ortega',
      estado: 'En Revisión',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceee7'),
      clase: 'Técnico',
      titulo: 'Plan de Mantenimiento',
      adjudicataria: 'Sara Medina',
      estado: 'Pendiente',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceee8'),
      clase: 'Administrativo',
      titulo: 'Solicitud de Recursos',
      adjudicataria: 'Daniel Herrera',
      estado: 'En Proceso',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceee9'),
      clase: 'Legal',
      titulo: 'Consulta Jurídica',
      adjudicataria: 'Laura Ruiz',
      estado: 'Aprobado',
    },
    {
      id: new ObjectId('67e2a2c1f3b8d4a8b57ceeea'),
      clase: 'Financiero',
      titulo: 'Informe de Deuda',
      adjudicataria: 'Víctor Ramos',
      estado: 'Pendiente',
    },
  ],
};
