import { ObjectId } from 'mongodb';
import { User } from './user/index.js';

export interface DB {
  users: User[];
}

export const db: DB = {
  users: [
    {
      _id: new ObjectId(),
      nombre: 'Carlos',
      apellidos: 'González Pérez',
      email: 'carlos.gonzalez@example.com',
      telefonoFijo: '910123456',
      telefonoMovil: '620123456',
      telefonoInstitucional: '930123456',
      clave: 'carlos123',
      rol: 'Administrador',
      esResponsable: true,
      esAutorizante: false,
    },
    {
      _id: new ObjectId(),
      nombre: 'María',
      apellidos: 'Martínez López',
      email: 'maria.martinez@example.com',
      telefonoFijo: '910234567',
      telefonoMovil: '620234567',
      telefonoInstitucional: '930234567',
      clave: 'maria456',
      rol: 'Usuario',
      esResponsable: false,
      esAutorizante: true,
    },
    {
      _id: new ObjectId(),
      nombre: 'Juan',
      apellidos: 'Rodríguez Sánchez',
      email: 'juan.rodriguez@example.com',
      telefonoFijo: '910345678',
      telefonoMovil: '620345678',
      telefonoInstitucional: '930345678',
      clave: 'juan789',
      rol: 'Supervisor',
      esResponsable: true,
      esAutorizante: true,
    },
    {
      _id: new ObjectId(),
      nombre: 'Laura',
      apellidos: 'García Ruiz',
      email: 'laura.garcia@example.com',
      telefonoFijo: '910456789',
      telefonoMovil: '620456789',
      telefonoInstitucional: '930456789',
      clave: 'laura101',
      rol: 'Usuario',
      esResponsable: false,
      esAutorizante: false,
    },
    {
      _id: new ObjectId(),
      nombre: 'Miguel',
      apellidos: 'Fernández Gómez',
      email: 'miguel.fernandez@example.com',
      telefonoFijo: '910567890',
      telefonoMovil: '620567890',
      telefonoInstitucional: '930567890',
      clave: 'miguel202',
      rol: 'Gerente',
      esResponsable: true,
      esAutorizante: false,
    },
    {
      _id: new ObjectId(),
      nombre: 'Ana',
      apellidos: 'Hernández Díaz',
      email: 'ana.hernandez@example.com',
      telefonoFijo: '910678901',
      telefonoMovil: '620678901',
      telefonoInstitucional: '930678901',
      clave: 'ana303',
      rol: 'Usuario',
      esResponsable: false,
      esAutorizante: true,
    },
    {
      _id: new ObjectId(),
      nombre: 'Pedro',
      apellidos: 'López Núñez',
      email: 'pedro.lopez@example.com',
      telefonoFijo: '910789012',
      telefonoMovil: '620789012',
      telefonoInstitucional: '930789012',
      clave: 'pedro404',
      rol: 'Supervisor',
      esResponsable: true,
      esAutorizante: false,
    },
    {
      _id: new ObjectId(),
      nombre: 'Sofía',
      apellidos: 'Ramírez Blanco',
      email: 'sofia.ramirez@example.com',
      telefonoFijo: '910890123',
      telefonoMovil: '620890123',
      telefonoInstitucional: '930890123',
      clave: 'sofia505',
      rol: 'Usuario',
      esResponsable: false,
      esAutorizante: false,
    },
    {
      _id: new ObjectId(),
      nombre: 'Javier',
      apellidos: 'Torres Vega',
      email: 'javier.torres@example.com',
      telefonoFijo: '910901234',
      telefonoMovil: '620901234',
      telefonoInstitucional: '930901234',
      clave: 'javier606',
      rol: 'Gerente',
      esResponsable: true,
      esAutorizante: true,
    },
    {
      _id: new ObjectId(),
      nombre: 'Elena',
      apellidos: 'Ortiz Castillo',
      email: 'elena.ortiz@example.com',
      telefonoFijo: '910012345',
      telefonoMovil: '620012345',
      telefonoInstitucional: '930012345',
      clave: 'elena707',
      rol: 'Administrador',
      esResponsable: true,
      esAutorizante: true,
    },
    {
      _id: new ObjectId(),
      nombre: 'Luis',
      apellidos: 'Morales Pineda',
      email: 'luis.morales@example.com',
      telefonoFijo: '910234678',
      telefonoMovil: '620234678',
      telefonoInstitucional: '930234678',
      clave: 'luis808',
      rol: 'Supervisor',
      esResponsable: true,
      esAutorizante: false,
    },
    {
      _id: new ObjectId(),
      nombre: 'Clara',
      apellidos: 'Pérez Gómez',
      email: 'clara.perez@example.com',
      telefonoFijo: '910345789',
      telefonoMovil: '620345789',
      telefonoInstitucional: '930345789',
      clave: 'clara909',
      rol: 'Usuario',
      esResponsable: false,
      esAutorizante: false,
    },
  ],
};
